In [1]:
import os
import glob
import pandas as pd
import re

# Define the base directory
base_dir = '.'  # Adjust this as needed

# Define the subdirectories
subdirs = ["spec0_0028", "spec0_0029", "spec0_00"]

In [2]:
# Initialize an empty list to hold individual DataFrames
dataframes = []

# Function to extract details from the filename
def extract_details(filename):
    base_name = os.path.basename(filename)
    match = re.match(r'SPECTRUM(\d{4})_processed_(\w+)_(\w+)', base_name)
    if match:
        id = int(match.group(1))
        plastic_type = match.group(2)
        color = match.group(3)
        return id, color, plastic_type
    return None

# Loop through each subdirectory
for subdir in subdirs:
    # Create the full path to the subdirectory
    full_path = os.path.join(base_dir, subdir)
    
    # Use glob to find all CSV files in the current subdirectory
    csv_files = glob.glob(os.path.join(full_path, '*.csv'))
    
    # Loop through each CSV file
    for csv_file in csv_files:
        # Extract details from the filename
        details = extract_details(csv_file)
        if details:
            id, color, plastic_type = details
            
            # Read the CSV file into a DataFrame
            df = pd.read_csv(csv_file)
            
            # Create a dictionary to hold the row data
            row_data = {
                'id': id,
                'color': color,
                'plastic type': plastic_type
            }
            
            # Add each wavelength and its corresponding value to the dictionary
            for _, row in df.iterrows():
                row_data[f'W_{row["W"]}'] = row['P']
            
            # Append the row data as a DataFrame to the list
            dataframes.append(pd.DataFrame([row_data]))

# Concatenate all DataFrames into a single DataFrame
combined_df = pd.concat(dataframes, ignore_index=True)

# Display the combined DataFrame
print(combined_df.head())

# Optionally, save the combined DataFrame to a new CSV file
combined_df.to_csv(os.path.join(base_dir, 'combined_data.csv'), index=False)

   id       color plastic type  W_347.96286  W_348.343445  W_348.723938  \
0  49  Transparan          PET     2.616119        13.855     21.593351
1  50  Trasnparan          PET          NaN           NaN           NaN
2  51  Transparan          PET          NaN           NaN           NaN
3  52       Putih          PET          NaN           NaN           NaN
4  53  Transparan          PET          NaN           NaN           NaN

   W_349.104431  W_349.484894  W_349.865326  W_350.245697  ...  W_345.297943  \
0     27.216747     31.555332     33.997162     36.206566  ...           NaN
1           NaN           NaN      1.875339      3.893140  ...           NaN
2           NaN           NaN           NaN           NaN  ...           NaN
3           NaN           NaN           NaN           NaN  ...           NaN
4           NaN      1.969096      5.772292      8.768127  ...           NaN

   W_345.678741  W_346.05954  W_346.440277  W_346.821014  W_342.250122  \
0           NaN          NaN           NaN           NaN           NaN
1           NaN          NaN           NaN           NaN           NaN
2           NaN          NaN           NaN           NaN           NaN
3           NaN          NaN           NaN           NaN           NaN
4           NaN          NaN           NaN           NaN           NaN

   W_344.155273  W_343.774323  W_342.631226  W_344.917114
0           NaN           NaN           NaN           NaN
1           NaN           NaN           NaN           NaN
2           NaN           NaN           NaN           NaN
3           NaN           NaN           NaN           NaN
4           NaN           NaN           NaN           NaN

[5 rows x 2049 columns]

In [3]:
combined_df

,id,color,plastic type,W_347.96286,W_348.343445,W_348.723938,W_349.104431,W_349.484894,W_349.865326,W_350.245697,...,W_345.297943,W_345.678741,W_346.05954,W_346.440277,W_346.821014,W_342.250122,W_344.155273,W_343.774323,W_342.631226,W_344.917114
0,49,Transparan,PET,2.616119,13.855000,21.593351,27.216747,31.555332,33.997162,36.206566,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50,Trasnparan,PET,NaN,NaN,NaN,NaN,NaN,1.875339,3.893140,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,Transparan,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,52,Putih,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,Transparan,PET,NaN,NaN,NaN,NaN,1.969096,5.772292,8.768127,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,92,Putih,PP,17.211960,16.651308,16.573664,15.910911,15.827883,15.687492,15.413787,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
112,94,Hijau,HDPE,1.862150,1.428124,1.631402,1.617272,1.638847,1.480557,1.501961,...,55.491104,57.187344,45.652142,33.75766,21.117834,65.836388,43.384533,46.402992,101.111137,43.975742
113,96,Merah,PP,6.684472,5.968463,5.746724,5.803707,5.403903,5.366490,5.383897,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
114,97,Transparan,LDPE,14.251799,12.735461,12.450594,11.924708,11.671423,11.441078,11.388009,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,99,Transparan,PET,29.223238,28.588245,28.497250,28.131346,28.196249,28.345205,28.471882,...,42.774426,56.249992,42.608505,NaN,NaN,49.466145,44.307804,25.539581,5.555681,24.096251