In [1]:
import pandas as pd

# Define the path to the combined data CSV file
combined_data_path = 'combined_data.csv'  # Adjust this as needed

# Read the combined data CSV file into a DataFrame
combined_df = pd.read_csv(combined_data_path)

# Remove the "W_" prefix from the wavelength columns
new_columns = {}
for col in combined_df.columns:
    if col.startswith('W_'):
        new_columns[col] = col[2:]  # Remove the "W_" prefix

# Rename the columns in the DataFrame
combined_df.rename(columns=new_columns, inplace=True)

# Sort the columns: First by 'id', 'color', 'plastic type', and then by wavelength
cols = ['id', 'color', 'plastic type'] + sorted([col for col in combined_df.columns if col not in ['id', 'color', 'plastic type']], key=float)
combined_df = combined_df[cols]

# Display the sorted DataFrame
combined_df.head()

,id,color,plastic type,340.344116,340.725372,341.106628,341.487823,341.869019,342.250122,342.631226,...,1025.887207,1026.171387,1026.455444,1026.73938,1027.023315,1027.307129,1027.590942,1027.874634,1028.158203,1028.441772
0,49,Transparan,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,50,Trasnparan,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,51,Transparan,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,52,Putih,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,53,Transparan,PET,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [2]:
# Filter the wavelength columns within the range 400-600
wavelength_cols = [col for col in combined_df.columns if col not in ['id', 'color', 'plastic type']]
wavelength_cols_filtered = [col for col in wavelength_cols if 400 <= float(col) <= 900]

# Check for missing values in the filtered wavelength columns
missing_values_count = combined_df[wavelength_cols_filtered].isnull().sum()

# Total number of elements in the range 400-600
total_elements = combined_df[wavelength_cols_filtered].shape[0] * len(wavelength_cols_filtered)

# Calculate the percentage of missing values
missing_values_percentage = (missing_values_count.sum() / total_elements) * 100

# Display the missing values count and percentage
print("Missing values in each column within the range:")
print(missing_values_count/combined_df.shape[0]*100)
print("\nTotal missing values in the range:", missing_values_count.sum())
print("Total elements in the range:", total_elements)
print("Percentage of missing values in the range: {:.2f}%".format(missing_values_percentage))

Missing values in each column within the range:
400.133331     0.000000
400.508789     0.000000
400.884216     0.000000
401.259613     0.000000
401.634949     0.000000
                ...
898.679749     1.724138
898.988342    10.344828
899.296814     6.896552
899.605225     4.310345
899.913696     7.758621
Length: 1454, dtype: float64

Total missing values in the range: 686
Total elements in the range: 168664
Percentage of missing values in the range: 0.41%

In [3]:
from sklearn.impute import SimpleImputer

# Impute missing values with the mean of each column within the specified range
imputer = SimpleImputer(strategy='mean')
combined_df[wavelength_cols_filtered] = imputer.fit_transform(combined_df[wavelength_cols_filtered])

In [4]:
missing_values_count = combined_df[wavelength_cols_filtered].isnull().sum()
print("total missing values after imputation:", missing_values_count.sum())

total missing values after imputation: 0

# Saving

In [13]:
import pandas as pd
from sklearn.impute import SimpleImputer

# Define the path to the combined data CSV file
combined_data_path = 'combined_data.csv'  # Adjust this as needed

# Read the combined data CSV file into a DataFrame
combined_df = pd.read_csv(combined_data_path)

# Remove the "W_" prefix from the wavelength columns
combined_df.columns = [col.split('_')[1] if col.startswith('W_') else col for col in combined_df.columns]

# Filter the wavelength columns within the range 400-900
wavelength_cols_filtered = [col for col in combined_df.columns if col != 'id' and col != 'color' and col != 'plastic type' and 400 <= float(col) <= 900]

# Subset the DataFrame to include only columns within the filtered wavelength range
subset_df = combined_df[['id', 'color', 'plastic type'] + wavelength_cols_filtered]

# Check if there are any numeric columns to perform imputation
if wavelength_cols_filtered:
    # Impute missing values with the mean of each column within the filtered wavelength range
    imputer = SimpleImputer(strategy='mean')
    subset_df[wavelength_cols_filtered] = imputer.fit_transform(subset_df[wavelength_cols_filtered])
else:
    print("No numeric columns within the specified wavelength range for imputation.")

# Optionally, save the imputed subset DataFrame to a new CSV file
subset_df.to_csv('imputed_combined_data_subset.csv', index=False)

C:\Users\User\AppData\Local\Temp\ipykernel_17276\809371129.py:23: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  subset_df[wavelength_cols_filtered] = imputer.fit_transform(subset_df[wavelength_cols_filtered])

   id       color plastic type  400.133331  400.508789  400.884216  \
0  49  Transparan          PET   60.351364   60.512665   60.626610
1  50  Trasnparan          PET   19.964344   20.043579   20.144825
2  51  Transparan          PET   16.811512   16.893469   17.011232
3  52       Putih          PET   75.843307   77.662079   79.593765
4  53  Transparan          PET   37.036633   37.331455   37.493233

   401.259613  401.634949  402.010254  402.385559  ...  897.136108  \
0   60.735283   60.927467   61.144253   61.224869  ...   88.963318
1   20.212513   20.396099   20.504927   20.559423  ...   47.218098
2   17.055092   17.121126   17.187664   17.169941  ...   78.036636
3   81.647659   83.815521   86.104065   88.202301  ...  274.305115
4   37.620407   37.839821   38.025574   38.077957  ...   82.184387

   897.444946  897.753723  898.062439  898.371155  898.679749  898.988342  \
0   88.568047   87.360184   85.711304   84.398033   83.330544   83.080719
1   46.385483   45.225742   44.367702   43.060097   41.979828   40.690384
2   77.393188   76.098213   74.713531   73.149994   72.379059   71.532295
3  272.992462  270.220642  267.294525  263.118225  260.135864  258.894653
4   80.849472   79.362396   77.899857   75.991585   74.288727   73.514656

   899.296814  899.605225  899.913696
0   82.002800   81.560013   81.482407
1   39.956558   39.300247   38.560486
2   70.585815   70.333099   69.396652
3  256.679901  255.601395  255.142395
4   72.317429   70.758453   69.727409

[5 rows x 1457 columns]

In [14]:
subset_df

,id,color,plastic type,400.133331,400.508789,400.884216,401.259613,401.634949,402.010254,402.385559,...,897.136108,897.444946,897.753723,898.062439,898.371155,898.679749,898.988342,899.296814,899.605225,899.913696
0,49,Transparan,PET,60.351364,60.512665,60.626610,60.735283,60.927467,61.144253,61.224869,...,88.963318,88.568047,87.360184,85.711304,84.398033,83.330544,83.080719,82.002800,81.560013,81.482407
1,50,Trasnparan,PET,19.964344,20.043579,20.144825,20.212513,20.396099,20.504927,20.559423,...,47.218098,46.385483,45.225742,44.367702,43.060097,41.979828,40.690384,39.956558,39.300247,38.560486
2,51,Transparan,PET,16.811512,16.893469,17.011232,17.055092,17.121126,17.187664,17.169941,...,78.036636,77.393188,76.098213,74.713531,73.149994,72.379059,71.532295,70.585815,70.333099,69.396652
3,52,Putih,PET,75.843307,77.662079,79.593765,81.647659,83.815521,86.104065,88.202301,...,274.305115,272.992462,270.220642,267.294525,263.118225,260.135864,258.894653,256.679901,255.601395,255.142395
4,53,Transparan,PET,37.036633,37.331455,37.493233,37.620407,37.839821,38.025574,38.077957,...,82.184387,80.849472,79.362396,77.899857,75.991585,74.288727,73.514656,72.317429,70.758453,69.727409
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111,92,Putih,PP,22.010794,21.991207,22.081758,22.051718,22.061535,22.068146,22.145014,...,49.122322,49.167603,49.366898,49.454952,49.123531,49.123661,48.800087,48.411701,47.173000,47.520115
112,94,Hijau,HDPE,5.387435,5.410059,5.418447,5.407332,5.420845,5.466297,5.499288,...,26.037668,25.950628,25.791368,25.497551,25.611464,25.750959,25.782856,25.315954,25.219360,24.680397
113,96,Merah,PP,4.756849,4.715742,4.700873,4.673644,4.645596,4.682441,4.700151,...,28.666117,28.547102,28.645178,28.797882,29.070797,28.889616,29.291142,29.141523,28.926725,28.823387
114,97,Transparan,LDPE,17.668196,17.732800,17.771029,17.798872,17.875439,17.889919,17.960592,...,38.489670,38.483730,38.414333,38.063812,38.238804,38.381062,37.937153,37.680748,37.689575,37.653881
115,99,Transparan,PET,31.800541,31.763964,31.759115,31.703302,31.680586,31.671595,31.696791,...,38.233681,38.436432,38.190315,37.948792,38.430115,38.801701,39.300556,39.160873,38.909870,38.204308